<?php
return array(
    'modules' => array(
        'ZF\\Apigility',
        'ZF\\Apigility\\Provider',
        'Phpro\\DoctrineHydrationModule',
        'ZF\\Apigility\\Doctrine\Server',
        'ZF\\Apigility\\Documentation',
        'AssetManager',
        'ZF\\ApiProblem',
        'ZF\\Configuration',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZfcBase',
        'ZfcUser',
        'DoctrineModule',
        'DoctrineORMModule',
        'ZfcUserDoctrineORM',
        'BjyAuthorize',
        'ZfcAdmin',
        'ZfcTwitterBootstrap',
        'Secretary',
        'SecretaryApi',
    ),
    'module_listener_options' => array(
        'config_glob_paths'    => array(
            '../../../config/autoload/{,*.}{global,test}.php',
        ),
        'module_paths' => array(
            '../../../module',
            '../../../vendor',
        ),
    ),
);
