<h2><?php echo $this->translate($this->title) ?></h2>
<table>
    <tr>
        <td style="padding: 3px 3px 3px 0;"><strong><?php echo $this->translate('Title') ?>:</strong></td>
        <td><?php echo $this->escapeHtml($this->note->getTitle())  ?></td>
    </tr>
    <tr>
        <td style="padding: 3px 3px 3px 0;"><strong><?php echo $this->translate('Group') ?>:</strong></td>
        <td><?php echo $this->escapeHtml($this->note->getGroup()->getName())  ?></td>
    </tr>
</table>
<p>
    <a href="<?php echo $this->host . $this->url('secretery/note', array('action' => 'view', 'id' => $this->note->getId())) ?>">
        <?php echo $this->translate('view it online') ?>
    </a>
</p>