<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sSecretery%s'), '<span class="sec-color">', '</span>') ?></h1>
    <p><?php echo $this->translate('A secure place for shared infos') ?>.</p>
    <div class="pic"></div>
</div>

<div class="row">
    <div class="span12">
        <?php if (!$this->zfcUserIdentity()): ?>
            <div class="homeLogin">
                <?php echo $this->zfcUserLoginWidget(array('redirect' => '/')); ?>
            </div>

        <?php elseif ('user' == $this->zfcUserIdentity()->getRoles()->first()->getRoleId()): ?>
        <?php
            $text  = $this->translate('Please create your private key to be able to add notes');
            $text .= '<br />';
            $text .= '<a href="' . $this->url('secretery/default', array('controller' => 'key')) . '">';
            $text .= ' &raquo; ' . $this->translate('Manage Key');
            $text .= '</a>';
            echo $this->ztbAlert($text, true, 'alert-error');
        ?>
        <?php else: ?>
            <h2><?php echo $this->translate('Hello World') ?></h2>
        <?php endif; ?>
    </div>
</div>
