<div class="row notes">
    <div class="span12">
        <h1><?php echo $this->translate('Add Note') ?></h1>
        <?php if (!empty($this->msg) && $this->msg[0] == 'error') {
            echo $this->ztbAlert($this->translate($this->msg[1]), false, 'alert-error');
        } ?>

        <fieldset>
            <legend><?php echo $this->translate('Create Note') ?></legend>
            <?php
                $form = $this->noteForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->ztbFormElement($form->get('title'));
                echo $this->ztbFormElement($form->get('content'));
                echo '<label class="checkbox">';
                echo $this->formElement($form->get('private'), 'append');
                echo $this->translate($form->get('private')->getLabel());
                echo '</label>';
                echo '<div class="form-actions">';
                echo $this->ztbFormElement($form->get('submit'));
                echo '</div>';
                echo $this->form()->closeTag();
            ?>
        </fieldset>
    </div>
</div>
