<div class="row notes">
    <div class="span12">
        <?php
        if (!empty($this->msg) && $this->msg[0] == 'error') {
            echo $this->ztbAlert($this->translate($this->msg[1]), false, 'alert-error');
        }
        ?>
    </div>
    <div class="span6">
        <h2><?php echo $this->translate('Add Note') ?></h2>
        <?php echo $this->render('secretery/note/_noteForm.phtml') ?>
    </div>
    <div class="span6 <?php if ($this->noteForm->get('private')->getValue() === true) { echo 'hide'; } ?>" id="shareNote">
        <h2><?php echo $this->translate('Add Note Members') ?></h2>
        <fieldset>
            <legend><?php echo $this->translate('Select Group') ?></legend>
            <?php
                echo $this->form()->openTag($this->groupForm);
                echo $this->formElement($this->groupForm->get('group'));
                echo $this->formElement($this->groupForm->get('submit'));
                echo $this->form()->closeTag();
            ?>
        </fieldset>
        <h4><?php echo $this->translate('Group Members') ?></h4>
        <div class="well" id="groupMembers"></div>
        <h4><?php echo $this->translate('Selected Group Members') ?></h4>
        <div class="well" id="selectedGroupMembers"><ul></ul></div>
    </div>
</div>
