<?php echo $this->doctype(); ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Secretery')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Secretery') ?></a>
                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation('Navigation')->menu()->setUlClass('nav'); ?>
                        <ul class="nav nav-stacked pull-right">
                            <?php if (!$this->zfcUserIdentity()): ?>
                            <li>
                                <a href="<?php echo $this->url('zfcuser/login') ?>">
                                    <?php echo $this->translate('Login') ?>
                                </a>
                            </li>
                            <?php else: ?>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <?php echo sprintf(
                                        $this->translate('User (%s)'),
                                        $this->zfcUserIdentity()->getDisplayname()
                                    ) ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="<?php echo $this->url('zfcuser') ?>">
                                            <?php echo $this->translate('View Details') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url('zfcuser/changeemail') ?>">
                                            <?php echo $this->translate('Change Email') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url('zfcuser/changepassword') ?>">
                                            <?php echo $this->translate('Change Password') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url('zfcuser/logout') ?>">
                                            <?php echo $this->translate('Logout') ?>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <?php endif ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php if (!$this->zfcUserIdentity()): ?>
                <?php if (!empty($this->routeMatch)): ?>
                    <?php echo $this->zfcUserLoginWidget(array('redirect' => 'home')); ?>
                <?php else: ?>
                    <?php echo $this->content; ?>
                <?php endif; ?>
            <?php else: ?>
                <?php echo $this->content; ?>
            <?php endif ?>
            <footer>
                <p>&copy; 2013 by Wesrc. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
