<div class="row" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="span12">
        <h1><?php echo $this->translate('Key Management') ?></h1>
        <?php echo $this->ztbAlert($this->translate($this->msg[1]), false, 'alert-' . $this->msg[0]) ?>
        <?php if ($this->activeMode == 'create') : ?>
        <div class="alert alert-block alert-error">
            <h4><?php echo $this->translate('Warning') ?></h4>
            <br />
            <ul>
                <li><?php echo $this->translate('Backup your key carefully (different places are a good idea)') ?></li>
                <li><?php echo $this->translate('The passphrase will be needed again to use the key - so save it!') ?></li>
            </ul>
        </div>
        <h2>
            <?php echo $this->translate('Copy the key to file and name it "something.pem"') ?>
        </h2>
        <pre><?php echo $this->escapeHtml($this->privKey) ?></pre>
        <?php endif; ?>
    </div>
</div>
