<div class="row groups">
    <div class="span12">
        <h1><?php
            if (isset($this->editMode)) {
                $actionTitle = 'Edit Group';
            } else {
                $actionTitle = 'Add Group';
            }
            echo $this->translate($actionTitle);
        ?></h1>
        <?php
            if (!empty($this->msg) && $this->msg[0] == 'error') {
                echo $this->ztbAlert($this->translate($this->msg[1]), false, 'alert-error');
            }
        ?>

        <?php echo $this->render('secretary/group/_groupForm.phtml') ?>

        <p class="backBtn">
            <a class="btn" href="<?php echo $this->url('secretary/group') ?>">
                <i class="icon-arrow-left"></i> <?php echo $this->translate('Back to overview') ?>
            </a>
        </p>
    </div>
</div>
