<div class="row notes">
    <div class="span12">
        <h1><?php echo $this->translate('Delete Note') ?></h1>
        <?php if (!empty($this->msg) && $this->msg[0] == 'error') {
            echo $this->ztbAlert($this->translate($this->msg[1]), false, 'alert-error');
        } ?>
        <?php if (true === $this->showKeyRequestForm): ?>
            <?php echo $this->render('secretary/note/_decryptForm.phtml') ?>
        <?php else: ?>
            <div class="alert alert-danger">
                <?php echo $this->translate('Do you really want to delete this note?') ?>
            </div>
            <?php echo $this->render('secretary/note/_noteView.phtml') ?>

            <div class="well well-small"><fieldset>
               <legend><?php echo $this->translate('Please confirm with key to delete note') ?></legend>
                <?php echo $this->ztbForm($keyRequestForm) ?>
           </fieldset></div>
            <p>
                <a class="btn btn-small" href="<?php echo $this->url('secretary/note'); ?>">
                    <?php echo $this->translate('Back to overview') ?>
                </a>
            </p>
        <?php endif; ?>
    </div>
</div>
