<div class="row notes">
    <div class="span12">
        <?php if (true === $this->showKeyRequestForm): ?>
            <h1><?php echo $this->translate('View Note') ?></h1>
            <?php
                if (!empty($this->msg)) {
                    echo $this->ztbAlert(
                        $this->translate($this->msg[1]),
                        false,
                        'alert-' . $this->msg[0]
                    );
                }
                echo $this->render('secretary/note/_decryptForm.phtml')
            ?>
        <?php else: ?>
            <?php echo $this->render('secretary/note/_noteView.phtml') ?>
            <p>
                <a class="btn btn-small btn-primary" href="<?php echo $this->url('secretary/note'); ?>">
                    <?php echo $this->translate('Back to overview') ?>
                </a>
            </p>
        <?php endif; ?>
    </div>
</div>
